@api=http://localhost:3000
###

POST {{api}}/text-body HTTP/1.1
Content-Type: text/plain

"Hello world"

###

POST {{api}}/json-body HTTP/1.1
Content-Type: application/json

{
    "a":"b"
}

### 

POST {{api}}/sum-of-numbers HTTP/1.1
Content-Type: application/json

{
    "numbers":[1,2,3]
}
###
# invalid json
POST {{api}}/sum-of-numbers HTTP/1.1
Content-Type: application/json

{
    "numbers":[a,2,3]
}
###
# invalid input type
POST {{api}}/sum-of-numbers HTTP/1.1
Content-Type: application/json

{
    "numbers":["a",2,3]
}

###
POST {{api}}/sum-of-numbers HTTP/1.1
Content-Type: application/json

{
    "numbers":[]
}